spring:
  profiles:
    active: dev
---
spring:
  profiles:
    active: prod
--- #api-server
lost-ark:
  user-auth-host: "https://lostark.game.onstove.com/Community/Free/Views/"
--- #swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true